# 使用说明 V4.4.0
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动

version: '3'
services:
  ruoyi-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: ruoyi-mysql
    image: ruoyi-mysql
    ports:
      - 3306:3306
    volumes:
      - ./ruoyi-mysql:/var/lib/mysql
    command: --lower_case_table_names=1

  ruoyi-redis:
    container_name: pigx-redis
    image: redis:6.2.6
    restart: always
    ports:
      - 6379:6379

  ruoyi-server:
    build:
      context: ./yudao-server
    restart: always
    container_name: ruoyi-server
    image: ruoyi-server
    ports:
      - 48080:48080